// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using riims.Data;

#nullable disable

namespace riims.Migrations
{
    [DbContext(typeof(RiimsDbContext))]
    [Migration("20240904174640_Seeding Data for NiveliGjuhesor")]
    partial class SeedingDataforNiveliGjuhesor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("riims.Models.Domain.Aftesite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Aftesite");
                });

            modelBuilder.Entity("riims.Models.Domain.Departamenti", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.ToTable("Departamenti");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a2c57ba-17fb-4f79-bcc4-cef9e704bf3d"),
                            Emri = "Menaxhment, Biznes dhe Ekonomi",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("1efbe13e-9b02-4860-8715-f80b035f93e2"),
                            Emri = "Shkenca Kompjuterike dhe Inxhineri",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("2c6b9320-7b40-4234-867c-03e3ae05f7ba"),
                            Emri = "Menaxhment i Mekatronikës",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("6d76ebfe-ef5b-43e5-8813-bbf98f2e7657"),
                            Emri = "Sistemet e Informacionit",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("dd90af7b-1852-42af-942d-c51fd8c6e854"),
                            Emri = "Arkitekturë dhe Planifikimi Hapësinor",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("f9944afc-5811-4960-96ab-d585f0210707"),
                            Emri = "Inxhineri Ndërtimore(Ndërtimtari) dhe Infrastrukturë",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("9e789309-441e-4f3f-af5f-69ba940902db"),
                            Emri = "Shkenca Politike",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("3f6e8e7a-58dc-4e60-9fad-fa4b2be412cd"),
                            Emri = "Juridik",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("dc1db886-3100-4ce9-99cc-493d88f603d5"),
                            Emri = "Media dhe Komunikim",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("b010567e-5b9c-461a-9d4b-1a9c36148f03"),
                            Emri = "Inxhineri e Energjisë",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("05251f11-0354-4d11-8dca-4422d284160b"),
                            Emri = "Politika Publike dhe Menaxhimi",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("7bb0e204-8a1a-4d40-b08f-81015d5c3c4e"),
                            Emri = "Infermieri",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("5d193df8-ef18-48d8-a722-7d94dbf636c6"),
                            Emri = "Farmaci",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("985167e8-cb59-4e1a-8bc8-268a3caf2911"),
                            Emri = "Stomatologji",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("273b38a2-4cd7-47e4-968b-d5d48d364edd"),
                            Emri = "Shkenca e Ushqimit dhe bioteknologji",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("7b6a59f2-d536-45c2-b981-ce54917084c0"),
                            Emri = "Dizajn i Integruar",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("571348c4-aadf-42b2-be6b-c2219e4dd845"),
                            Emri = "AgriKulturë dhe Inxhineri e Ambientit",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("4debc353-f2cc-4d75-82c8-0e356999a77a"),
                            Emri = "Arti dhe Mediat Digjitale",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("9aa12dbb-746c-41de-88b5-19da7de10516"),
                            Emri = "Muzika Moderne, Prodhimi Digjital dhe Menaxhimi",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("7da76f05-491c-44b4-9377-7e99c3ffd97b"),
                            Emri = "Teknik i Anesteziologjisë",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("7300a7d2-a6a0-4ca4-96c6-940e7b0c865e"),
                            Emri = "Teknik i Radiologjisë",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("b47eb467-7e2c-476c-b50b-25751692b447"),
                            Emri = "Aktrim",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        },
                        new
                        {
                            Id = new Guid("1e962ebf-9721-4fab-b489-6f0a1de1f0e8"),
                            Emri = "Psikologji",
                            InstitucioniId = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48")
                        });
                });

            modelBuilder.Entity("riims.Models.Domain.Edukimi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("FushaStudimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lokacioni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("NiveliAkademikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("NiveliAkademikId");

                    b.HasIndex("UserId");

                    b.ToTable("Edukimi");
                });

            modelBuilder.Entity("riims.Models.Domain.Eksperienca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LlojiLokacionit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlojiPunesimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacioni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Eksperienca");
                });

            modelBuilder.Entity("riims.Models.Domain.Gjuhet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmriGjuhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gjuhet");
                });

            modelBuilder.Entity("riims.Models.Domain.HonorsAndAwards", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dataEleshimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("HonorsAndAwards");
                });

            modelBuilder.Entity("riims.Models.Domain.Institucioni", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Institucioni");

                    b.HasData(
                        new
                        {
                            Id = new Guid("496cc2c1-cc09-4c64-a53d-9529c2486b48"),
                            Emri = "UBT"
                        },
                        new
                        {
                            Id = new Guid("94c1f26d-3feb-4b96-91e5-68d077a5b804"),
                            Emri = "UP"
                        });
                });

            modelBuilder.Entity("riims.Models.Domain.Licensat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredentialId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLeshimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSkadimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Licensat");
                });

            modelBuilder.Entity("riims.Models.Domain.MbikqyresITemave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartamentiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("studenti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulliTemes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentiId");

                    b.HasIndex("UserId");

                    b.ToTable("MbikqyresITemave");
                });

            modelBuilder.Entity("riims.Models.Domain.NiveliAkademik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("lvl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NiveliAkademik");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe75fb45-6c06-4324-a2a2-092b6e4a493e"),
                            lvl = "B.Sc."
                        },
                        new
                        {
                            Id = new Guid("6f67cd1a-d096-4dc6-a011-f733be57f74c"),
                            lvl = "M.Sc."
                        },
                        new
                        {
                            Id = new Guid("f53512ec-7466-4a98-90bd-862ca65e5cfd"),
                            lvl = "Ph.D."
                        });
                });

            modelBuilder.Entity("riims.Models.Domain.NiveliGjuhesor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Niveli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NiveliGjuhesor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e52fa674-6854-4539-aeb8-89e716698f21"),
                            Niveli = "A1"
                        },
                        new
                        {
                            Id = new Guid("c7c2b680-c679-4de2-83d0-28464165f115"),
                            Niveli = "A2"
                        },
                        new
                        {
                            Id = new Guid("4f965348-1db2-4212-88bf-1bc868338209"),
                            Niveli = "B1"
                        },
                        new
                        {
                            Id = new Guid("a5c0e948-be3d-4ebd-beba-8b0a9fc0285b"),
                            Niveli = "B2"
                        },
                        new
                        {
                            Id = new Guid("2ea9d919-b3ea-4d0e-9e76-311c6955c4e7"),
                            Niveli = "C1"
                        },
                        new
                        {
                            Id = new Guid("81ebd457-1e9a-480b-bde1-d62196c51d75"),
                            Niveli = "C2"
                        });
                });

            modelBuilder.Entity("riims.Models.Domain.Projekti", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("asocohet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("collaborators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emriProjektit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("riims.Models.Domain.Publikimi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AutoriKryesor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataPublikimi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartamentiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkuPublikimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlojiPublikimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentiId");

                    b.HasIndex("UserId");

                    b.ToTable("Publikimi");
                });

            modelBuilder.Entity("riims.Models.Domain.PunaVullnetare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("PunaVullnetare");
                });

            modelBuilder.Entity("riims.Models.Domain.Specializimet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("aftesiteEfituara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataEFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataEMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("llojiIspecializimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lokacionit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nrKredive")
                        .HasColumnType("int");

                    b.Property<string>("pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Specializimet");
                });

            modelBuilder.Entity("riims.Models.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NiveliAkademikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dataELindjes")
                        .HasColumnType("datetime2");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gjinia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numriTelefonit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NiveliAkademikId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("riims.Models.Domain.UserGjuhet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GjuhaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NiveliGjuhesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GjuhaId");

                    b.HasIndex("NiveliGjuhesorId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGjuhet");
                });

            modelBuilder.Entity("riims.Models.Domain.Aftesite", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("Aftesia")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Aftesite")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.Departamenti", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("Departamentet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");
                });

            modelBuilder.Entity("riims.Models.Domain.Edukimi", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("Edukimet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.NiveliAkademik", "NiveliAkademik")
                        .WithMany("Edukimet")
                        .HasForeignKey("NiveliAkademikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Edukimet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("NiveliAkademik");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.Eksperienca", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("Eksperiencat")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Eksperiencat")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.HonorsAndAwards", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("HonorsAndAwards")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("HonorsAndAwards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.Licensat", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("Licensat")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Licensat")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.MbikqyresITemave", b =>
                {
                    b.HasOne("riims.Models.Domain.Departamenti", "Departamenti")
                        .WithMany("Mbikqyresit")
                        .HasForeignKey("DepartamentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("MbiKqyresitETemave")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamenti");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.Projekti", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("Projektet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Projektet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.Publikimi", b =>
                {
                    b.HasOne("riims.Models.Domain.Departamenti", "Departamenti")
                        .WithMany("Publikimet")
                        .HasForeignKey("DepartamentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Publikimet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamenti");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.PunaVullnetare", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("PunetVullnetare")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("PunetVullnetare")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.Specializimet", b =>
                {
                    b.HasOne("riims.Models.Domain.Institucioni", "Institucioni")
                        .WithMany("Specializimet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Specializimet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.User", b =>
                {
                    b.HasOne("riims.Models.Domain.NiveliAkademik", null)
                        .WithMany("Users")
                        .HasForeignKey("NiveliAkademikId");
                });

            modelBuilder.Entity("riims.Models.Domain.UserGjuhet", b =>
                {
                    b.HasOne("riims.Models.Domain.Gjuhet", "Gjuha")
                        .WithMany("UserGjuhet")
                        .HasForeignKey("GjuhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.NiveliGjuhesor", "NiveliGjuhesor")
                        .WithMany("UserGjuhet")
                        .HasForeignKey("NiveliGjuhesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("riims.Models.Domain.User", "User")
                        .WithMany("Gjuhet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gjuha");

                    b.Navigation("NiveliGjuhesor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("riims.Models.Domain.Departamenti", b =>
                {
                    b.Navigation("Mbikqyresit");

                    b.Navigation("Publikimet");
                });

            modelBuilder.Entity("riims.Models.Domain.Gjuhet", b =>
                {
                    b.Navigation("UserGjuhet");
                });

            modelBuilder.Entity("riims.Models.Domain.Institucioni", b =>
                {
                    b.Navigation("Aftesia");

                    b.Navigation("Departamentet");

                    b.Navigation("Edukimet");

                    b.Navigation("Eksperiencat");

                    b.Navigation("HonorsAndAwards");

                    b.Navigation("Licensat");

                    b.Navigation("Projektet");

                    b.Navigation("PunetVullnetare");

                    b.Navigation("Specializimet");
                });

            modelBuilder.Entity("riims.Models.Domain.NiveliAkademik", b =>
                {
                    b.Navigation("Edukimet");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("riims.Models.Domain.NiveliGjuhesor", b =>
                {
                    b.Navigation("UserGjuhet");
                });

            modelBuilder.Entity("riims.Models.Domain.User", b =>
                {
                    b.Navigation("Aftesite");

                    b.Navigation("Edukimet");

                    b.Navigation("Eksperiencat");

                    b.Navigation("Gjuhet");

                    b.Navigation("HonorsAndAwards");

                    b.Navigation("Licensat");

                    b.Navigation("MbiKqyresitETemave");

                    b.Navigation("Projektet");

                    b.Navigation("Publikimet");

                    b.Navigation("PunetVullnetare");

                    b.Navigation("Specializimet");
                });
#pragma warning restore 612, 618
        }
    }
}
